### ISSUE TITLE
Information about keywords that are 2-grams or 3-grams

### ISSUE THREAD

**Issue by igormis** [SkBlaz/rakun#4]
1. I have tried the code and it is impressive, however I have some difficulties to show in the output not single words, but 2-grams or 3-grams that represent a keyword for specific text. Any info on how to tune the hyperparameters?

2. Concerning the hyperparameters could you explain some of them, such as:
-                    "pair_diff_length":2,
-                    "bigram_count_threshold":2,
-                    "num_tokens":[1,2],
- 		   "max_similar" : 3, ## n most similar can show up n times
- 		   "max_occurrence" : 3} ## maximum frequency overall

Thanks.

**Comment by SkBlaz** [comment]
Hello @igormis !

Thanks for the issue. Indeed, I'm realizing the hyperparameters were poorly explained. Hence, I've added more detailed descriptions here: https://github.com/SkBlaz/rakun#hyperparameter-explanation

Further, I've added an example where only 2-gram keywords are detected here:
https://github.com/SkBlaz/rakun/blob/master/examples/multi_term.py

Hopefully, this resolves the confusion.

**Comment by igormis** [comment]
@SkBlaz perfect, tnx. What about lemmatize, can it be used as hyperparam and in which way?

**Comment by SkBlaz** [comment]
Indeed, I forgot that one. I've updated the multi_term.py to include
lemmatization, as well as the hyperparameters description. Hope this helps!

**Comment by igormis** [comment]
Perfect, now its much more understandable, tnx @SkBlaz

**Comment by SkBlaz** [comment]
No problem! I'd suggest you close the issue if you deem it solved, thanks!

>
