### ISSUE TITLE
 module 'gensim.models.fasttext' has no attribute 'load_facebook_vectors'

### ISSUE THREAD

**Issue by Raidus** [SkBlaz/rakun#7]
Hi,

when using fasttext in google colab, I'll get the error 
` module 'gensim.models.fasttext' has no attribute 'load_facebook_vectors'`

Any idea?

**Comment by SkBlaz** [comment]
Hello, it seems like gensim's api has changed, will have a look asap

**Comment by SkBlaz** [comment]
hello @Raidus , it seems gensim's API is fine, see the [example](https://github.com/SkBlaz/rakun/blob/master/examples/example_embedding.py). Which version are you using?

**Comment by Raidus** [comment]
@SkBlaz I am using version 3.6.0 in colab.

**Comment by SkBlaz** [comment]
Did you try to run the [example](https://github.com/SkBlaz/rakun/blob/master/examples/example_embedding.py)? (you need pretrained vectors for this)

**Comment by hawekotte** [comment]
While it has been a bit, I wanted to pop in to say that while the requirements file targets [`gensim >= 3.8.0`](https://github.com/SkBlaz/rakun/blob/master/requirements.txt#L5), Colab installs `3.6.0` (which isn't proper). So a quick solution is to just run `! pip3 install --upgrade gensim` (to upgrade to the current `v4.0.1`) and things should be back up and running.

**Comment by SkBlaz** [comment]
This was indeed the issue. As the requirements are clearly stated, I think we can safely close this one.
