### ISSUE TITLE
Packages should never overwrite the root logger.

### ISSUE THREAD

**Issue by mrkkollo** [SkBlaz/rakun#8]
https://github.com/SkBlaz/rakun/blob/master/mrakun/__init__.py#L29
```python
logging.basicConfig(format='%(asctime)s - %(message)s',
                    datefmt='%d-%b-%y %H:%M:%S')
logging.getLogger().setLevel(logging.INFO)
```
Using getLogger() without any arguments makes it default to a root logger, and thus
overwrites its level against the users wishes. This makes integrating the package into bigger applications
very difficult as it robs control of the logs from the developer.

Although I'm not aware of what the good practice for setting up loggers for a package is, replacing those lines with the following significantly reduces log clutter:
```python
logging.basicConfig(format='%(asctime)s - %(message)s', datefmt='%d-%b-%y %H:%M:%S')
logging.getLogger(__name__).setLevel(logging.INFO)
```

**Comment by SkBlaz** [comment]
Thanks! This makes sense should it be included into a larger app (wasn't focusing on that at the time of writing this package) Could you open a pull request which addresses this issue perhaps?

**Comment by mrkkollo** [comment]
Sure, I can do it but it might have a delay of a few days.

**Comment by SkBlaz** [comment]
Great, thanks!

**Comment by rsirel** [comment]
Please fix! This is a problematic issue when processing many documents.

**Comment by SkBlaz** [comment]
Hey, fixed it as suggested in https://pypi.org/project/mrakun/0.45/ (see
the new commit)

**Comment by rsirel** [comment]
Thanks!
